networks:
  # The presence of these objects is sufficient to define them
  expense: {}

volumes:
  mysql:


services:
 # docker run -d --name mysql --network expense mysql:1.0.0 
  mysql:
    image: arun596/mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

 # docker run -d --name backend --network expense backend:1.0.0 

  backend:
   image: arun596/backend:1.0.0
   command: sh -c "sleep 5 && node /opt/backend/index.js"
   networks:
     - expense
   container_name: backend
   depends_on:
     - mysql

 # docker run -d --name frontend --network expense -p 80:80 frontend:1.0.0 

  frontend:
   image: arun596/frontend:1.0.0
   ports:
     - 80:80
   networks:
     - expense
   container_name: frontend
   depends_on:
     - backend
